# Generated by Django 3.2.4 on 2021-06-02 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='', max_length=400)),
                ('evidence1', models.CharField(default='', max_length=400)),
                ('evidence2', models.CharField(default='', max_length=400)),
                ('evidence3', models.CharField(default='', max_length=400)),
                ('evidence4', models.CharField(default='', max_length=400)),
                ('evidence5', models.CharField(default='', max_length=400)),
                ('T_F', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
